### ISSUE TITLE
cant start lavalink

### ISSUE THREAD

**Issue by Tomato6966** [DuncteBot/skybot-lavalink-plugin#13]
```
06:27:27 root@het-cloud-milrato test → java -jar Lavalink.jar 
2022-12-10 18:27:31.031  INFO 1903759 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 18.0.2.1 on het-cloud-milrato with PID 1903759 (/home/lavalinks/test/Lavalink.jar started by root in /home/lavalinks/test)
2022-12-10 18:27:31.035  INFO 1903759 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2022-12-10 18:27:32.062  INFO 1903759 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'lavalink-filter-plugin' version 0.0.1
2022-12-10 18:27:32.074  INFO 1903759 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded lavalink-filter-plugin-0.0.1.jar (1 classes)
2022-12-10 18:27:32.075  INFO 1903759 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'lavasrc' version 3.1.7
2022-12-10 18:27:32.103  INFO 1903759 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded lavasrc-plugin-3.1.7.jar (22 classes)
2022-12-10 18:27:32.107  WARN 1903759 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$28825506]: Constructor threw exception; nested exception is java.lang.RuntimeException: Error loading ./plugins/skybot-lavalink-plugin-1.4.1.jar
2022-12-10 18:27:32.120  INFO 1903759 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-12-10 18:27:32.144 ERROR 1903759 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$28825506]: Constructor threw exception; nested exception is java.lang.RuntimeException: Error loading ./plugins/skybot-lavalink-plugin-1.4.1.jar
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at lavalink.server.Launcher.launchPluginBootstrap(Launcher.kt:131) ~[classes!/:na]
        at lavalink.server.Launcher.main(Launcher.kt:123) ~[classes!/:na]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[Lavalink.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$28825506]: Constructor threw exception; nested exception is java.lang.RuntimeException: Error loading ./plugins/skybot-lavalink-plugin-1.4.1.jar
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.18.jar!/:5.3.18]
        ... 23 common frames omitted
Caused by: java.lang.RuntimeException: Error loading ./plugins/skybot-lavalink-plugin-1.4.1.jar
        at lavalink.server.bootstrap.PluginManager.loadJars(PluginManager.kt:114) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager.<init>(PluginManager.kt:29) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$28825506.<init>(<generated>) ~[classes!/:na]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.18.jar!/:5.3.18]
        ... 25 common frames omitted
Caused by: java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1474) ~[na:na]
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1482) ~[na:na]
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1320) ~[na:na]
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1282) ~[na:na]
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[na:na]
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[na:na]
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318) ~[na:na]
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:284) ~[na:na]
        at lavalink.server.bootstrap.PluginManager.loadJar(PluginManager.kt:124) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager.loadJars(PluginManager.kt:112) ~[classes!/:na]
        ... 31 common frames omitted

06:27:32 root@het-cloud-milrato test → 
```
error occurss since latest version 1.4.1

**Comment by Tomato6966** [comment]
ubuntu 20, note that it does not always happen

**Comment by duncte123** [comment]
Seems like the file you downloaded is corrupted

**Comment by Tomato6966** [comment]
okay so it shouldn't happen, cause it just happened after like 2 days of running

**Comment by duncte123** [comment]
> okay so it shouldn't happen, cause it just happened after like 2 days of running

All i can tell by these logs is that the file you downloaded is corrupted, i suggest that you use the maven repository if you're not already
