### ISSUE TITLE
403 when downloading the plugin?

### ISSUE THREAD

**Issue by DaliborTrampota** [DuncteBot/skybot-lavalink-plugin#15]
Server returned HTTP response code: 403 for URL: https://m2.duncte123.dev/releases/com/dunctebot/skybot-lavalink-plugin/1.4.1/skybot-lavalink-plugin-1.4.1.jar

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$be5cfb9d]: Constructor threw exception; nested exception is java.io.IOException: Server returned HTTP response code: 403 for URL: https://m2.duncte123.dev/releases/com/dunctebot/skybot-lavalink-plugin/1.4.1/skybot-lavalink-plugin-1.4.1.jar
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:296) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.6.jar!/:2.6.6]
        at lavalink.server.Launcher.launchPluginBootstrap(Launcher.kt:131) [classes!/:na]
        at lavalink.server.Launcher.main(Launcher.kt:123) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_361]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_361]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_361]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_361]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [Lavalink.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$be5cfb9d]: Constructor threw exception; nested exception is java.io.IOException: Server returned HTTP response code: 403 for URL: 
https://m2.duncte123.dev/releases/com/dunctebot/skybot-lavalink-plugin/1.4.1/skybot-lavalink-plugin-1.4.1.jar
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.3.18.jar!/:5.3.18]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311) ~[spring-beans-5.3.18.jar!/:5.3.18]
        ... 25 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://m2.duncte123.dev/releases/com/dunctebot/skybot-lavalink-plugin/1.4.1/skybot-lavalink-plugin-1.4.1.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_361]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_361]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[na:1.8.0_361]
        at java.net.URL.openStream(Unknown Source) ~[na:1.8.0_361]
        at lavalink.server.bootstrap.PluginManager.downloadJar(PluginManager.kt:80) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager.manageDownloads(PluginManager.kt:74) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager.<init>(PluginManager.kt:26) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$be5cfb9d.<init>(<generated>) ~[classes!/:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_361]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_361]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_361]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_361]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.18.jar!/:5.3.18]
        ... 27 common frames omitted
```

**Comment by DaliborTrampota** [comment]
downloaded it manually, weird

**Comment by duncte123** [comment]
If you downloaded the file a lot it could be that cloudflare blocked you
