### ISSUE TITLE
TikTok Source still has issues

### ISSUE THREAD

**Issue by Abadima** [DuncteBot/skybot-lavalink-plugin#22]
## Description
When trying TikTok urls, it still doesn't play anything.

## Version info
**Client used:** Poru

Output of `java -version`: 
```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Temurin-19.0.2+7 (build 19.0.2+7)
```

2023-08-07 13:31:58.678  WARN 26 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Suspicious exception for playback of 7114016045630754054
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: The audio codec used in the track is not supported.
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.loadAudioTrack(MpegAudioTrack.java:65) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:41) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.5.0.jar!/:na]
        at com.dunctebot.sourcemanagers.Mp3Track.loadStream(Mp3Track.java:58) ~[skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.dunctebot.sourcemanagers.tiktok.TikTokAudioTrack.loadStream(TikTokAudioTrack.java:90) ~[skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.dunctebot.sourcemanagers.tiktok.TikTokAudioTrack.process(TikTokAudioTrack.java:76) ~[skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:346) ~[lavaplayer-1.5.0.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-78-generic
  java.vendor: Eclipse Adoptium
  java.version: 19.0.2
  java.runtime.version: 19.0.2+7
  java.vm.version: 19.0.2+7

**Comment by duncte123** [comment]
What is the plugin version you are using?

**Comment by Abadima** [comment]
> What is the plugin version you are using?

I use thé latest, v1.4.2

**Comment by zoli456** [comment]
You need to use the pre release version. I have just tested it on my bot because my provider finally updated to java 17. It should work with lavalink 3-4 .
https://github.com/DuncteBot/skybot-lavalink-plugin/releases/tag/PRE_1.5.0_22

**Comment by Abadima** [comment]
Works btw! I had to manually download the file though, since "PRE_1.5.0_22" & "1.5.0" doesn't work yet when trying what you said here:
https://github.com/DuncteBot/skybot-lavalink-plugin#adding-to-lavalink

Otherwise, thank you!
