### ISSUE TITLE
Mixcloud not working

### ISSUE THREAD

**Issue by Hackleyyy** [DuncteBot/skybot-lavalink-plugin#24]
### LOGS:

2023-09-25 05:52:19.396  INFO 1032 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.mixcloud.com/Hirockn/the-100-best-tracks-2020-hip-hop-rb-pops-etc-the-weeknd-dababy-dua-lipa-juice-wrld-etc/"
2023-09-25 05:52:19.721 ERROR 1032 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item https://www.mixcloud.com/Hirockn/the-100-best-tracks-2020-hip-hop-rb-pops-etc-the-weeknd-dababy-dua-lipa-juice-wrld-etc/

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a MixCloud track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.5.0.jar!/:na]
        at com.dunctebot.sourcemanagers.mixcloud.MixcloudAudioSourceManager.loadItem(MixcloudAudioSourceManager.java:75) ~[jar:file:D:\...\....\....\...\lavalink\.\plugins\skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[lavaplayer-1.5.0.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 17.0.8
  java.runtime.version: 17.0.8+9-LTS-211
  java.vm.version: 17.0.8+9-LTS-211
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html><html><head><title>Mixcloud</title><link rel="dns-prefetch" href="//thumbnailer.mixcloud.com"><link rel="dns-prefetch" href="//waveform.mixcloud.com"><link rel="icon" href="/assets/client/www/ed0ff20015e714ae803a.ico" sizes="16x16 32x32"><link rel="icon" href="/assets/client/www/822bb1471c1c302ecb45.png" sizes="16x16"><link rel="icon" href="/assets/client/www/3c11b02e5df74fc7f1b7.png" sizes="32x32"><link rel="icon" href="/assets/client/www/c1381b1a0145cac85cab.png" sizes="48x48"><"[truncated 2001 chars]; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4703) ~[jackson-databind-2.13.2.2.jar!/:2.13.2.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076) ~[jackson-databind-2.13.2.2.jar!/:2.13.2.2]
        at com.sedmelluq.discord.lavaplayer.tools.JsonBrowser.parse(JsonBrowser.java:204) ~[lavaplayer-1.5.0.jar!/:na]

at com.dunctebot.sourcemanagers.mixcloud.MixcloudAudioSourceManager.extractTrackInfoGraphQl(MixcloudAudioSourceManager.java:132) ~[jar:file:D:\...\....\....\...\lavalink\.\plugins\skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.dunctebot.sourcemanagers.mixcloud.MixcloudAudioSourceManager.loadItemOnce(MixcloudAudioSourceManager.java:86) ~[jar:file:D:\...\....\....\...\lavalink\.\plugins\skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.dunctebot.sourcemanagers.mixcloud.MixcloudAudioSourceManager.loadItem(MixcloudAudioSourceManager.java:72) ~[jar:file:D:\...\....\....\...\lavalink\.\plugins\skybot-lavalink-plugin-1.4.2.jar!/:na]
        ... 7 common frames omitted

2023-09-25 05:52:19.721 ERROR 1032 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a MixCloud track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.5.0.jar!/:na]
        at com.dunctebot.sourcemanagers.mixcloud.MixcloudAudioSourceManager.loadItem(MixcloudAudioSourceManager.java:75) ~[jar:file:D:\...\....\....\...\lavalink\.\plugins\skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[lavaplayer-1.5.0.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 17.0.8
  java.runtime.version: 17.0.8+9-LTS-211
  java.vm.version: 17.0.8+9-LTS-211
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<!DOCTYPE html><html><head><title>Mixcloud</title><link rel="dns-prefetch" href="//thumbnailer.mixcloud.com"><link rel="dns-prefetch" href="//waveform.mixcloud.com"><link rel="icon" href="/assets/client/www/ed0ff20015e714ae803a.ico" sizes="16x16 32x32"><link rel="icon" href="/assets/client/www/822bb1471c1c302ecb45.png" sizes="16x16"><link rel="icon" href="/assets/client/www/3c11b02e5df74fc7f1b7.png" sizes="32x32"><link rel="icon" href="/assets/client/www/c1381b1a0145cac85cab.png" sizes="48x48"><"[truncated 2001 chars]; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005) ~[jackson-core-2.13.2.jar!/:2.13.2]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802) ~[jackson-core-2.13.2.jar!/:2.13.2]

at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4703) ~[jackson-databind-2.13.2.2.jar!/:2.13.2.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076) ~[jackson-databind-2.13.2.2.jar!/:2.13.2.2]
        at com.sedmelluq.discord.lavaplayer.tools.JsonBrowser.parse(JsonBrowser.java:204) ~[lavaplayer-1.5.0.jar!/:na]
        at com.dunctebot.sourcemanagers.mixcloud.MixcloudAudioSourceManager.extractTrackInfoGraphQl(MixcloudAudioSourceManager.java:132) ~[jar:file:D:\...\....\....\...\lavalink\.\plugins\skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.dunctebot.sourcemanagers.mixcloud.MixcloudAudioSourceManager.loadItemOnce(MixcloudAudioSourceManager.java:86) ~[jar:file:D:\...\....\....\...\lavalink\.\plugins\skybot-lavalink-plugin-1.4.2.jar!/:na]
        at com.dunctebot.sourcemanagers.mixcloud.MixcloudAudioSourceManager.loadItem(MixcloudAudioSourceManager.java:72) ~[jar:file:D:\...\....\....\...\lavalink\.\plugins\skybot-lavalink-plugin-1.4.2.jar!/:na]
        ... 7 common frames omitted

**Comment by duncte123** [comment]
Looks like mixcloud changed their graphql interface, should be an easy fix

**Comment by duncte123** [comment]
Please try version `1.5.1`, also keep in mind that this is on a new repository: `https://maven.lavalink.dev/releases`
