### ISSUE TITLE
hi i have this

### ISSUE THREAD

**Issue by louisplayz-inc-ask** [DuncteBot/skybot-lavalink-plugin#4]
i have a error 

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$45b0f168]: Constructor threw exception; nested exception is java.lang.RuntimeException: Error loading .\plugins\skybot-lavalink-plugin-1.3.0.jar
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
        at lavalink.server.Launcher.launchPluginBootstrap(Launcher.kt:132) ~[classes!/:na]
        at lavalink.server.Launcher.main(Launcher.kt:124) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[Lavalink.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[Lavalink.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$45b0f168]: Constructor threw exception; nested exception is java.lang.RuntimeException: Error loading .\plugins\skybot-lavalink-plugin-1.3.0.jar
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        ... 25 common frames omitted
Caused by: java.lang.RuntimeException: Error loading .\plugins\skybot-lavalink-plugin-1.3.0.jar
        at lavalink.server.bootstrap.PluginManager.loadJars(PluginManager.kt:114) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager.<init>(PluginManager.kt:29) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager$$EnhancerBySpringCGLIB$$45b0f168.<init>(<generated>) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
        ... 27 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.dunctebot.lavalinkplugin.DuncteBotConfig$Sources
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[na:na]
        at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:872) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
        at lavalink.server.bootstrap.PluginManager.loadJar(PluginManager.kt:143) ~[classes!/:na]
        at lavalink.server.bootstrap.PluginManager.loadJars(PluginManager.kt:112) ~[classes!/:na]
        ... 35 common frames omitted

```

Output of `java -version`:
```
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```

**Comment by duncte123** [comment]
Are you loading the plugin via the config file or are you downloading a jar?

**Comment by louisplayz-inc-ask** [comment]
hi, we are not available right now we will send you back if we are back

**Comment by louisplayz-inc-ask** [comment]
From the jar file 

Sorry about the previous comment it was my auto reply of my email

**Comment by duncte123** [comment]
Could you try the proper loading via the configuration file?
Also, I suggest you just turn that auto-reply off for GitHub emails.

**Comment by louisplayz-inc-ask** [comment]
How do I do that to load from the config

**Comment by duncte123** [comment]
It's described in the readme file

**Comment by louisplayz-inc-ask** [comment]
Ah okey 


I do it tomorrow 

For me it's nicht

**Comment by louisplayz-inc-ask** [comment]
This is my stuff that previously loaded + worked but now not 
![Screenshot_20220208-220451.png](https://user-images.githubusercontent.com/98408573/153075527-d95c00ec-4514-4949-8d95-efbb84f8315f.png)

**Comment by duncte123** [comment]
As described [here (adding to lavalink)](https://github.com/DuncteBot/skybot-lavalink-plugin#adding-to-lavalink), you need to add a plugins block to the lavalink top-level block. With that, it will automatically download the plugin.

**Comment by louisplayz-inc-ask** [comment]
still the same

**Comment by duncte123** [comment]
I cannot reproduce your issue, I suggest you use java 11.0.4 instead of java 17 since lavalink is made for java 11

**Comment by louisplayz-inc-ask** [comment]
i found the problem at me 

i have `Java SE Development Kit 17.0.2`

and i delete that and now its working but i want to do a minecraft server but that need `Java SE Development Kit 17.0.2`

but i am going to think about to do a hosting

**Comment by louisplayz-inc-ask** [comment]
or i hope that it can fixt
