### ISSUE TITLE
Pornhub playback broken: Missing video url

### ISSUE THREAD

**Issue by DarrenOfficial** [DuncteBot/skybot-lavalink-plugin#6]
## Description
When I try to play this https://www.pornhub.com/view_video.php?viewkey=ph5fc5ef73cfc87, it returns "Video url missing on playback page". Full logs here
```bash
2022-03-02 09:49:05.397  INFO 23020 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.pornhub.com/view_video.php?viewkey=ph5fc5ef73cfc87"
2022-03-02 09:49:05.917  INFO 23020 --- [er-2-thread-160] lavalink.server.player.AudioLoader       : Loaded track Tons of hard cobs getting grabbed
2022-03-02 09:49:06.258  INFO 23020 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"play","guildId":"938025248610201620","track":"QAAAmwIAIVRvbnMgb2YgaGFyZCBjb2JzIGdldHRpbmcgZ3JhYmJlZAAJcG9ybmh1YnR2AAAAAAAALuAAD3BoNWZjNWVmNzNjZmM4NwABAD5odHRwczovL3d3dy5wb3JuaHViLmNvbS92aWV3X3ZpZGVvLnBocD92aWV3a2V5PXBoNWZjNWVmNzNjZmM4NwAHcG9ybmh1YgAAAAAAAAAA"}             
2022-03-02 09:49:07.087 ERROR 23020 --- [ck-1-thread-186] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of ph5fc5ef73cfc87

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Video url missing on playback page
        at com.dunctebot.sourcemanagers.pornhub.PornHubAudioTrack.loadMp4Url(PornHubAudioTrack.java:164) ~[skybot-lavalink-plugin-1.3.3.jar!/:na]
        at com.dunctebot.sourcemanagers.pornhub.PornHubAudioTrack.loadFromMediaInfo(PornHubAudioTrack.java:93) ~[skybot-lavalink-plugin-1.3.3.jar!/:na]
        at com.dunctebot.sourcemanagers.pornhub.PornHubAudioTrack.getPlaybackUrl(PornHubAudioTrack.java:51) ~[skybot-lavalink-plugin-1.3.3.jar!/:na]
        at com.dunctebot.sourcemanagers.Mp3Track.loadStream(Mp3Track.java:54) ~[skybot-lavalink-plugin-1.3.3.jar!/:na]
        at com.dunctebot.sourcemanagers.Mp3Track.process(Mp3Track.java:49) ~[skybot-lavalink-plugin-1.3.3.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-fork-1.3.97.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-fork-1.3.97.jar!/:na]                     
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.97-original
  os.arch: amd64
  os.name: Linux
  os.version: 4.19.0-18-amd64
  java.vendor: Azul Systems, Inc.
  java.version: 17.0.2
  java.runtime.version: 17.0.2+8-LTS
  java.vm.version: 17.0.2+8-LTS

2022-03-02 09:49:07.449  INFO 23020 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"stop","guildId":"938025248610201620"}
```

![](https://i.dpaste.org/rcqPXu7t/direct)

This is my application.yml, this should be correct ig
![](https://i.dpaste.org/gquLahSN/direct)

## Version info
**Client used:** erela.js
**Client Code:** https://git.darrennathanael.com/DarrenOfficial/DiscordMusic

Output of `java -version`:
```java
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

**Comment by duncte123** [comment]
I cannot reproduce this issue on version 1.3.3, the following code helped me test it
```java
public class PHtest {
    public static void main(String[] args) throws Exception {
        final var link = "https://www.pornhub.com/view_video.php?viewkey=ph5fc5ef73cfc87";
        final var mngr = new PornHubAudioSourceManager();

        final var track = (PornHubAudioTrack) mngr.loadItem(null, new AudioReference(link, null));

        System.out.println(
            track.loadFromMediaInfo() // private method, reflection was used to access it
        );
    }
}
```

**Comment by DarrenOfficial** [comment]
> I cannot reproduce this issue on version 1.3.3, the following code helped me test it
> 
> ```java
> public class PHtest {
>     public static void main(String[] args) throws Exception {
>         final var link = "https://www.pornhub.com/view_video.php?viewkey=ph5fc5ef73cfc87";
>         final var mngr = new PornHubAudioSourceManager();
> 
>         final var track = (PornHubAudioTrack) mngr.loadItem(null, new AudioReference(link, null));
> 
>         System.out.println(
>             track.loadFromMediaInfo() // private method, reflection was used to access it
>         );
>     }
> }
> ```

Is it possible that the issue happen because I'm using IPv6 address?

**Comment by duncte123** [comment]
It is possible that the cookies sent by pornhub are invalid if you are rotating over the IP. But that would not be something I have configured

I can do this fine via an ipv6 address
